{
 "title": "Tickets Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Tickets created",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ticket_created_counter_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tickets closed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ticket_status_closed_counter_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket resolved",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ticket_status_resolved_counter_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tickets created over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(ticket_created_counter_seconds_count[$__rate_interval])",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Tickets Status change over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "increase(ticket_status_closed_counter_seconds_count[1m])",
     "legendFormat": "Closed"
    },
    {
     "expr": "increase(ticket_status_reopened_counter_seconds_count[1m])",
     "legendFormat": "Reopened"
    },
    {
     "expr": "increase(ticket_status_resolved_counter_seconds_count[1m])",
     "legendFormat": "Resolved"
    },
    {
     "expr": "increase(ticket_status_open_counter_seconds_count[1m])",
     "legendFormat": "Opened"
    },
    {
     "expr": "increase(ticket_status_in_progress_counter_seconds_count[1m])",
     "legendFormat": "In progress"
    }
   ]
  }
 ]
}